const players = [
{ name: "Derrick Henry", college: "Alabama" },
{ name: "Julio Jones", college: "Alabama" },
{ name: "Tua Tagovailoa", college: "Alabama" },
{ name: "Minkah Fitzpatrick", college: "Alabama" },
{ name: "Amari Cooper", college: "Alabama" },
{ name: "Mark Ingram", college: "Alabama" },
{ name: "Najee Harris", college: "Alabama" },
{ name: "DeVonta Smith", college: "Alabama" },
{ name: "Jaylen Waddle", college: "Alabama" },
{ name: "Mac Jones", college: "Alabama" },
{ name: "Brian Robinson Jr.", college: "Alabama" },
{ name: "C.J. Mosley", college: "Alabama" },
{ name: "Jonathan Allen", college: "Alabama" },
{ name: "Quinnen Williams", college: "Alabama" },
{ name: "Evan Neal", college: "Alabama" },
{ name: "O.J. Howard", college: "Alabama" },
{ name: "Calvin Ridley", college: "Alabama" },
{ name: "Derrick Thomas", college: "Alabama" },
{ name: "Joe Namath", college: "Alabama" },
{ name: "Ken Stabler", college: "Alabama" },

{ name: "Rob Gronkowski", college: "Arizona" },
{ name: "Nick Foles", college: "Arizona" },
{ name: "Tedy Bruschi", college: "Arizona" },
{ name: "Lance Briggs", college: "Arizona" },
{ name: "Gronkowski", college: "Arizona" },
{ name: "Chris Mills", college: "Arizona" },
{ name: "Andre Iguodala", college: "Arizona" },
{ name: "Deandre Ayton", college: "Arizona" },
{ name: "Aaron Gordon", college: "Arizona" },
{ name: "Jason Terry", college: "Arizona" },
{ name: "Richard Jefferson", college: "Arizona" },
{ name: "Mike Bibby", college: "Arizona" },
{ name: "Channing Frye", college: "Arizona" },
{ name: "Derrick Williams", college: "Arizona" },

{ name: "Cam Newton", college: "Auburn" },
{ name: "Bo Jackson", college: "Auburn" },
{ name: "Frank Thomas", college: "Auburn" },
{ name: "Ronnie Brown", college: "Auburn" },
{ name: "Carnell Williams", college: "Auburn" },
{ name: "Takeo Spikes", college: "Auburn" },
{ name: "Karlos Dansby", college: "Auburn" },
{ name: "Auburn", college: "Auburn" },
{ name: "Charles Barkley", college: "Auburn" },
{ name: "Chuck Person", college: "Auburn" },
{ name: "Jabari Smith Jr.", college: "Auburn" },
{ name: "Walker Kessler", college: "Auburn" },

{ name: "Robert Griffin III", college: "Baylor" },
{ name: "Corey Coleman", college: "Baylor" },
{ name: "Josh Gordon", college: "Baylor" },
{ name: "Xavien Howard", college: "Baylor" },
{ name: "Denzel Mims", college: "Baylor" },
{ name: "Kendall Wright", college: "Baylor" },
{ name: "Taurean Prince", college: "Baylor" },
{ name: "Quincy Acy", college: "Baylor" },
{ name: "Royce O'Neale", college: "Baylor" },
{ name: "Davion Mitchell", college: "Baylor" },
{ name: "Jared Butler", college: "Baylor" },
{ name: "Jeremy Sochan", college: "Baylor" },
{ name: "Deshaun Watson", college: "Clemson" },
{ name: "Trevor Lawrence", college: "Clemson" },
{ name: "DeAndre Hopkins", college: "Clemson" },
{ name: "Mike Williams", college: "Clemson" },
{ name: "Tee Higgins", college: "Clemson" },
{ name: "Sammy Watkins", college: "Clemson" },
{ name: "C.J. Spiller", college: "Clemson" },
{ name: "Christian Wilkins", college: "Clemson" },
{ name: "Dexter Lawrence", college: "Clemson" },
{ name: "Vic Beasley", college: "Clemson" },
{ name: "Isaiah Simmons", college: "Clemson" },
{ name: "Brian Dawkins", college: "Clemson" },

{ name: "Kordell Stewart", college: "Colorado" },
{ name: "Eric Bieniemy", college: "Colorado" },
{ name: "Mason Crosby", college: "Colorado" },
{ name: "Laviska Shenault Jr.", college: "Colorado" },
{ name: "Nate Solder", college: "Colorado" },
{ name: "Chauncey Billups", college: "Colorado" },
{ name: "Alec Burks", college: "Colorado" },
{ name: "Spencer Dinwiddie", college: "Colorado" },
{ name: "Derrick White", college: "Colorado" },

{ name: "Zion Williamson", college: "Duke" },
{ name: "Kyrie Irving", college: "Duke" },
{ name: "Brandon Ingram", college: "Duke" },
{ name: "RJ Barrett", college: "Duke" },
{ name: "Jayson Tatum", college: "Duke" },
{ name: "Paolo Banchero", college: "Duke" },
{ name: "Grayson Allen", college: "Duke" },
{ name: "JJ Redick", college: "Duke" },
{ name: "Grant Hill", college: "Duke" },
{ name: "Christian Laettner", college: "Duke" },
{ name: "Elton Brand", college: "Duke" },
{ name: "Carlos Boozer", college: "Duke" },
{ name: "Shane Battier", college: "Duke" },
{ name: "Daniel Jones", college: "Duke" },
{ name: "Laken Tomlinson", college: "Duke" },
{ name: "Tim Tebow", college: "Florida" },
{ name: "Percy Harvin", college: "Florida" },
{ name: "Kyle Pitts", college: "Florida" },
{ name: "Kadarius Toney", college: "Florida" },
{ name: "Joe Haden", college: "Florida" },
{ name: "Fred Taylor", college: "Florida" },
{ name: "Emmitt Smith", college: "Florida" },
{ name: "Al Horford", college: "Florida" },
{ name: "Bradley Beal", college: "Florida" },
{ name: "Udonis Haslem", college: "Florida" },
{ name: "Mike Miller", college: "Florida" },
{ name: "David Lee", college: "Florida" },
{ name: "Chandler Parsons", college: "Florida" },

{ name: "Jameis Winston", college: "Florida State" },
{ name: "Dalvin Cook", college: "Florida State" },
{ name: "Jalen Ramsey", college: "Florida State" },
{ name: "Derwin James", college: "Florida State" },
{ name: "Deion Sanders", college: "Florida State" },
{ name: "Anquan Boldin", college: "Florida State" },
{ name: "Warrick Dunn", college: "Florida State" },
{ name: "Xavier Rhodes", college: "Florida State" },
{ name: "Sam Cassell", college: "Florida State" },
{ name: "Jonathan Isaac", college: "Florida State" },
{ name: "Malik Beasley", college: "Florida State" },
{ name: "Patrick Williams", college: "Florida State" },

{ name: "Davante Adams", college: "Fresno State" },
{ name: "Derek Carr", college: "Fresno State" },
{ name: "David Carr", college: "Fresno State" },
{ name: "Ryan Mathews", college: "Fresno State" },
{ name: "Paul George", college: "Fresno State" },

{ name: "Matthew Stafford", college: "Georgia" },
{ name: "Nick Chubb", college: "Georgia" },
{ name: "Sony Michel", college: "Georgia" },
{ name: "Todd Gurley", college: "Georgia" },
{ name: "A.J. Green", college: "Georgia" },
{ name: "Roquan Smith", college: "Georgia" },
{ name: "Travon Walker", college: "Georgia" },
{ name: "Brock Bowers", college: "Georgia" },
{ name: "Klay Thompson", college: "Georgia" }, 
{ name: "Kentavious Caldwell-Pope", college: "Georgia" },
{ name: "Anthony Edwards", college: "Georgia" },
{ name: "Calvin Johnson", college: "Georgia Tech" },
{ name: "Demaryius Thomas", college: "Georgia Tech" },
{ name: "Harrison Butker", college: "Georgia Tech" },
{ name: "Shaq Mason", college: "Georgia Tech" },
{ name: "Chris Bosh", college: "Georgia Tech" },
{ name: "Thaddeus Young", college: "Georgia Tech" },
{ name: "Iman Shumpert", college: "Georgia Tech" },
{ name: "Josh Okogie", college: "Georgia Tech" },

{ name: "John Stockton", college: "Gonzaga" },
{ name: "Domantas Sabonis", college: "Gonzaga" },
{ name: "Rui Hachimura", college: "Gonzaga" },
{ name: "Kelly Olynyk", college: "Gonzaga" },
{ name: "Jalen Suggs", college: "Gonzaga" },
{ name: "Chet Holmgren", college: "Gonzaga" },
{ name: "Zach Collins", college: "Gonzaga" },
{ name: "Corey Kispert", college: "Gonzaga" },

{ name: "Case Keenum", college: "Houston" },
{ name: "Ed Oliver", college: "Houston" },
{ name: "D'Eriq King", college: "Houston" },
{ name: "Andre Ware", college: "Houston" },
{ name: "Hakeem Olajuwon", college: "Houston" },
{ name: "Clyde Drexler", college: "Houston" },
{ name: "Quentin Grimes", college: "Houston" },
{ name: "Fabian White Jr.", college: "Houston" },

{ name: "Dick Butkus", college: "Illinois" },
{ name: "Red Grange", college: "Illinois" },
{ name: "Simeon Rice", college: "Illinois" },
{ name: "Whitney Mercilus", college: "Illinois" },
{ name: "Deron Williams", college: "Illinois" },
{ name: "Kendrick Nunn", college: "Illinois" },
{ name: "Ayo Dosunmu", college: "Illinois" },
{ name: "Meyers Leonard", college: "Illinois" },

{ name: "Peyton Manning", college: "Indiana" },
{ name: "Tevin Coleman", college: "Indiana" },
{ name: "Jordan Howard", college: "Indiana" },
{ name: "Cody Latimer", college: "Indiana" },
{ name: "Victor Oladipo", college: "Indiana" },
{ name: "Eric Gordon", college: "Indiana" },
{ name: "OG Anunoby", college: "Indiana" },
{ name: "Thomas Bryant", college: "Indiana" },
{ name: "George Kittle", college: "Iowa" },
{ name: "T.J. Hockenson", college: "Iowa" },
{ name: "Noah Fant", college: "Iowa" },
{ name: "Micah Hyde", college: "Iowa" },
{ name: "Brandon Scherff", college: "Iowa" },
{ name: "Tyler Linderbaum", college: "Iowa" },
{ name: "Luka Garza", college: "Iowa" },
{ name: "Keegan Murray", college: "Iowa" },
{ name: "Kris Murray", college: "Iowa" },

{ name: "Breece Hall", college: "Iowa State" },
{ name: "Brock Purdy", college: "Iowa State" },
{ name: "Allen Lazard", college: "Iowa State" },
{ name: "David Montgomery", college: "Iowa State" },
{ name: "Xavier Hutchinson", college: "Iowa State" },
{ name: "Georges Niang", college: "Iowa State" },
{ name: "Tyrese Haliburton", college: "Iowa State" },
{ name: "Monte Morris", college: "Iowa State" },

{ name: "Paul Pierce", college: "Kansas" },
{ name: "Andrew Wiggins", college: "Kansas" },
{ name: "Joel Embiid", college: "Kansas" },
{ name: "Devonte' Graham", college: "Kansas" },
{ name: "Marcus Morris", college: "Kansas" },
{ name: "Markieff Morris", college: "Kansas" },
{ name: "Ochai Agbaji", college: "Kansas" },
{ name: "Christian Braun", college: "Kansas" },
{ name: "Danny Manning", college: "Kansas" },
{ name: "Kirk Hinrich", college: "Kansas" },
{ name: "Nick Collison", college: "Kansas" },

{ name: "Tyler Lockett", college: "Kansas State" },
{ name: "Jordy Nelson", college: "Kansas State" },
{ name: "Darren Sproles", college: "Kansas State" },
{ name: "Colin Klein", college: "Kansas State" },
{ name: "Michael Beasley", college: "Kansas State" },
{ name: "Jacob Pullen", college: "Kansas State" },
{ name: "Dean Wade", college: "Kansas State" },

{ name: "Anthony Davis", college: "Kentucky" },
{ name: "Devin Booker", college: "Kentucky" },
{ name: "Karl-Anthony Towns", college: "Kentucky" },
{ name: "John Wall", college: "Kentucky" },
{ name: "Bam Adebayo", college: "Kentucky" },
{ name: "De'Aaron Fox", college: "Kentucky" },
{ name: "Jamal Murray", college: "Kentucky" },
{ name: "Tyler Herro", college: "Kentucky" },
{ name: "Shai Gilgeous-Alexander", college: "Kentucky" },
{ name: "PJ Washington", college: "Kentucky" },
{ name: "Keldon Johnson", college: "Kentucky" },
{ name: "Rajon Rondo", college: "Kentucky" },
{ name: "Eric Bledsoe", college: "Kentucky" },
{ name: "Willie Cauley-Stein", college: "Kentucky" },
{ name: "Nerlens Noel", college: "Kentucky" },
{ name: "Julius Randle", college: "Kentucky" },
{ name: "Joe Burrow", college: "LSU" },
{ name: "Ja'Marr Chase", college: "LSU" },
{ name: "Justin Jefferson", college: "LSU" },
{ name: "Odell Beckham Jr.", college: "LSU" },
{ name: "Jarvis Landry", college: "LSU" },
{ name: "Patrick Peterson", college: "LSU" },
{ name: "Tyrann Mathieu", college: "LSU" },
{ name: "Leonard Fournette", college: "LSU" },
{ name: "Clyde Edwards-Helaire", college: "LSU" },
{ name: "Danielle Hunter", college: "LSU" },
{ name: "Shaquille O'Neal", college: "LSU" },
{ name: "Ben Simmons", college: "LSU" },
{ name: "Naz Reid", college: "LSU" },

{ name: "Lamar Jackson", college: "Louisville" },
{ name: "Teddy Bridgewater", college: "Louisville" },
{ name: "DeVante Parker", college: "Louisville" },
{ name: "Jaire Alexander", college: "Louisville" },
{ name: "Mitch McConnell", college: "Louisville" }, 
{ name: "Donovan Mitchell", college: "Louisville" },
{ name: "Montrezl Harrell", college: "Louisville" },
{ name: "Gorgui Dieng", college: "Louisville" },
{ name: "Terry Rozier", college: "Louisville" },

{ name: "Stefon Diggs", college: "Maryland" },
{ name: "D.J. Moore", college: "Maryland" },
{ name: "Vernon Davis", college: "Maryland" },
{ name: "Torrey Smith", college: "Maryland" },
{ name: "Yannick Ngakoue", college: "Maryland" },
{ name: "Kevin Huerter", college: "Maryland" },
{ name: "Alex Len", college: "Maryland" },
{ name: "Greivis Vásquez", college: "Maryland" },

{ name: "DeAngelo Williams", college: "Memphis" },
{ name: "Antonio Gibson", college: "Memphis" },
{ name: "Darrell Henderson", college: "Memphis" },
{ name: "Paxton Lynch", college: "Memphis" },
{ name: "Derrick Rose", college: "Memphis" },
{ name: "Penny Hardaway", college: "Memphis" },
{ name: "James Wiseman", college: "Memphis" },
{ name: "Precious Achiuwa", college: "Memphis" },

{ name: "Ray Lewis", college: "Miami" },
{ name: "Ed Reed", college: "Miami" },
{ name: "Michael Irvin", college: "Miami" },
{ name: "Frank Gore", college: "Miami" },
{ name: "Willis McGahee", college: "Miami" },
{ name: "Andre Johnson", college: "Miami" },
{ name: "Sean Taylor", college: "Miami" },
{ name: "Clinton Portis", college: "Miami" },
{ name: "Greg Olsen", college: "Miami" },
{ name: "Jimmy Graham", college: "Miami" },
{ name: "Vince Wilfork", college: "Miami" },
{ name: "Devin Hester", college: "Miami" },
{ name: "Reggie Wayne", college: "Miami" },
{ name: "Tom Brady", college: "Michigan" },
{ name: "Charles Woodson", college: "Michigan" },
{ name: "Aidan Hutchinson", college: "Michigan" },
{ name: "Donovan Peoples-Jones", college: "Michigan" },
{ name: "Nico Collins", college: "Michigan" },
{ name: "Jabrill Peppers", college: "Michigan" },
{ name: "Brandon Graham", college: "Michigan" },
{ name: "Zavier Simpson", college: "Michigan" },
{ name: "Franz Wagner", college: "Michigan" },
{ name: "Moritz Wagner", college: "Michigan" },
{ name: "Tim Hardaway Jr.", college: "Michigan" },
{ name: "Trey Burke", college: "Michigan" },

{ name: "Kirk Cousins", college: "Michigan State" },
{ name: "Le'Veon Bell", college: "Michigan State" },
{ name: "Kenneth Walker III", college: "Michigan State" },
{ name: "Connor Cook", college: "Michigan State" },
{ name: "Draymond Green", college: "Michigan State" },
{ name: "Jaren Jackson Jr.", college: "Michigan State" },
{ name: "Gary Harris", college: "Michigan State" },
{ name: "Miles Bridges", college: "Michigan State" },
{ name: "Denzel Valentine", college: "Michigan State" },

{ name: "Antoine Winfield Jr.", college: "Minnesota" },
{ name: "Rashod Bateman", college: "Minnesota" },
{ name: "Tyler Johnson", college: "Minnesota" },
{ name: "Marion Barber III", college: "Minnesota" },
{ name: "Jamal Mashburn", college: "Minnesota" }, 
{ name: "Kris Humphries", college: "Minnesota" },
{ name: "Amir Coffey", college: "Minnesota" },

{ name: "Dak Prescott", college: "Mississippi State" },
{ name: "Chris Jones", college: "Mississippi State" },
{ name: "Jeffery Simmons", college: "Mississippi State" },
{ name: "Fletcher Cox", college: "Mississippi State" },
{ name: "Darius Slay", college: "Mississippi State" },
{ name: "Reggie Perry", college: "Mississippi State" },

{ name: "Drew Lock", college: "Missouri" },
{ name: "Blaine Gabbert", college: "Missouri" },
{ name: "Jeremy Maclin", college: "Missouri" },
{ name: "Sheldon Richardson", college: "Missouri" },
{ name: "Michael Porter Jr.", college: "Missouri" },
{ name: "Jordan Clarkson", college: "Missouri" },
{ name: "DeMarre Carroll", college: "Missouri" },
{ name: "Ndamukong Suh", college: "Nebraska" },
{ name: "Ameer Abdullah", college: "Nebraska" },
{ name: "Rex Burkhead", college: "Nebraska" },
{ name: "Prince Amukamara", college: "Nebraska" },
{ name: "Eric Crouch", college: "Nebraska" },
{ name: "Tyronn Lue", college: "Nebraska" },

{ name: "Michael Jordan", college: "North Carolina" },
{ name: "Vince Carter", college: "North Carolina" },
{ name: "Antawn Jamison", college: "North Carolina" },
{ name: "Ty Lawson", college: "North Carolina" },
{ name: "Harrison Barnes", college: "North Carolina" },
{ name: "Cole Anthony", college: "North Carolina" },
{ name: "Coby White", college: "North Carolina" },
{ name: "Danny Green", college: "North Carolina" },
{ name: "Rasheed Wallace", college: "North Carolina" },
{ name: "Jerry Stackhouse", college: "North Carolina" },
{ name: "Mitch Trubisky", college: "North Carolina" },
{ name: "Julius Peppers", college: "North Carolina" },

{ name: "Philip Rivers", college: "NC State" },
{ name: "Russell Wilson", college: "NC State" },
{ name: "Bradley Chubb", college: "NC State" },
{ name: "Nyheim Hines", college: "NC State" },
{ name: "Torry Holt", college: "NC State" },
{ name: "Dennis Smith Jr.", college: "NC State" },
{ name: "TJ Warren", college: "NC State" },

{ name: "Joe Montana", college: "Notre Dame" },
{ name: "Tim Brown", college: "Notre Dame" },
{ name: "Jerome Bettis", college: "Notre Dame" },
{ name: "Brady Quinn", college: "Notre Dame" },
{ name: "Golden Tate", college: "Notre Dame" },
{ name: "Chase Claypool", college: "Notre Dame" },
{ name: "Kyle Rudolph", college: "Notre Dame" },
{ name: "Manti Te'o", college: "Notre Dame" },
{ name: "Arike Ogunbowale", college: "Notre Dame" },

{ name: "C.J. Stroud", college: "Ohio State" },
{ name: "Justin Fields", college: "Ohio State" },
{ name: "Ezekiel Elliott", college: "Ohio State" },
{ name: "Chase Young", college: "Ohio State" },
{ name: "Nick Bosa", college: "Ohio State" },
{ name: "Joey Bosa", college: "Ohio State" },
{ name: "Terry McLaurin", college: "Ohio State" },
{ name: "Garrett Wilson", college: "Ohio State" },
{ name: "Chris Olave", college: "Ohio State" },
{ name: "Michael Thomas", college: "Ohio State" },
{ name: "Marvin Harrison Jr.", college: "Ohio State" },
{ name: "D'Angelo Russell", college: "Ohio State" },
{ name: "Mike Conley", college: "Ohio State" },
{ name: "Jared Sullinger", college: "Ohio State" },
{ name: "Baker Mayfield", college: "Oklahoma" },
{ name: "Kyler Murray", college: "Oklahoma" },
{ name: "Jalen Hurts", college: "Oklahoma" },
{ name: "CeeDee Lamb", college: "Oklahoma" },
{ name: "Marquise Brown", college: "Oklahoma" },
{ name: "Adrian Peterson", college: "Oklahoma" },
{ name: "Trent Williams", college: "Oklahoma" },
{ name: "Sam Bradford", college: "Oklahoma" },
{ name: "Buddy Hield", college: "Oklahoma" },
{ name: "Trae Young", college: "Oklahoma" },
{ name: "Blake Griffin", college: "Oklahoma" },

{ name: "Barry Sanders", college: "Oklahoma State" },
{ name: "Thurman Thomas", college: "Oklahoma State" },
{ name: "Mason Rudolph", college: "Oklahoma State" },
{ name: "James Washington", college: "Oklahoma State" },
{ name: "Dez Bryant", college: "Oklahoma State" },
{ name: "Marcus Smart", college: "Oklahoma State" },
{ name: "Cade Cunningham", college: "Oklahoma State" },
{ name: "Tony Allen", college: "Oklahoma State" },

{ name: "Eli Manning", college: "Ole Miss" },
{ name: "Archie Manning", college: "Ole Miss" },
{ name: "DK Metcalf", college: "Ole Miss" },
{ name: "A.J. Brown", college: "Ole Miss" },
{ name: "Laquon Treadwell", college: "Ole Miss" },
{ name: "Patrick Willis", college: "Ole Miss" },
{ name: "Marshall Henderson", college: "Ole Miss" },

{ name: "Marcus Mariota", college: "Oregon" },
{ name: "Justin Herbert", college: "Oregon" },
{ name: "De'Anthony Thomas", college: "Oregon" },
{ name: "LaMichael James", college: "Oregon" },
{ name: "Kayvon Thibodeaux", college: "Oregon" },
{ name: "Haloti Ngata", college: "Oregon" },
{ name: "Dillon Brooks", college: "Oregon" },
{ name: "Chris Boucher", college: "Oregon" },
{ name: "Jordan Bell", college: "Oregon" },

{ name: "Brandin Cooks", college: "Oregon State" },
{ name: "Steven Jackson", college: "Oregon State" },
{ name: "Chad Johnson", college: "Oregon State" },
{ name: "T.J. Houshmandzadeh", college: "Oregon State" },
{ name: "Gary Payton II", college: "Oregon State" },
{ name: "Drew Eubanks", college: "Oregon State" },
{ name: "Saquon Barkley", college: "Penn State" },
{ name: "Micah Parsons", college: "Penn State" },
{ name: "Allen Robinson", college: "Penn State" },
{ name: "Chris Godwin", college: "Penn State" },
{ name: "Jahan Dotson", college: "Penn State" },
{ name: "Sean Lee", college: "Penn State" },
{ name: "Paul Posluszny", college: "Penn State" },
{ name: "Lamar Stevens", college: "Penn State" },

{ name: "Larry Fitzgerald", college: "Pittsburgh" },
{ name: "Aaron Donald", college: "Pittsburgh" },
{ name: "LeSean McCoy", college: "Pittsburgh" },
{ name: "James Conner", college: "Pittsburgh" },
{ name: "Tyler Boyd", college: "Pittsburgh" },
{ name: "Kenny Pickett", college: "Pittsburgh" },
{ name: "Steven Adams", college: "Pittsburgh" },
{ name: "DeJuan Blair", college: "Pittsburgh" },

{ name: "Drew Brees", college: "Purdue" },
{ name: "Rondale Moore", college: "Purdue" },
{ name: "George Karlaftis", college: "Purdue" },
{ name: "Raheem Mostert", college: "Purdue" },
{ name: "Caleb Swanigan", college: "Purdue" },
{ name: "Carsen Edwards", college: "Purdue" },
{ name: "JaJuan Johnson", college: "Purdue" },

{ name: "Ray Rice", college: "Rutgers" },
{ name: "Devin McCourty", college: "Rutgers" },
{ name: "Jason McCourty", college: "Rutgers" },
{ name: "Mohamed Sanu", college: "Rutgers" },
{ name: "Kenny Britt", college: "Rutgers" },
{ name: "Isiah Pacheco", college: "Rutgers" },
{ name: "Geo Baker", college: "Rutgers" },
{ name: "Ron Harper Jr.", college: "Rutgers" },

{ name: "Jadeveon Clowney", college: "South Carolina" },
{ name: "Deebo Samuel", college: "South Carolina" },
{ name: "Alshon Jeffery", college: "South Carolina" },
{ name: "Stephon Gilmore", college: "South Carolina" },
{ name: "Hayden Hurst", college: "South Carolina" },
{ name: "Sindarius Thornwell", college: "South Carolina" },
{ name: "PJ Dozier", college: "South Carolina" },
{ name: "Andrew Luck", college: "Stanford" },
{ name: "Christian McCaffrey", college: "Stanford" },
{ name: "Richard Sherman", college: "Stanford" },
{ name: "Zach Ertz", college: "Stanford" },
{ name: "Davis Mills", college: "Stanford" },
{ name: "Ty Montgomery", college: "Stanford" },
{ name: "Brook Lopez", college: "Stanford" },
{ name: "Robin Lopez", college: "Stanford" },
{ name: "KZ Okpala", college: "Stanford" },

{ name: "Donovan McNabb", college: "Syracuse" },
{ name: "Marvin Harrison", college: "Syracuse" },
{ name: "Dwight Freeney", college: "Syracuse" },
{ name: "Chandler Jones", college: "Syracuse" },
{ name: "Carmelo Anthony", college: "Syracuse" },
{ name: "Dion Waiters", college: "Syracuse" },
{ name: "Michael Carter-Williams", college: "Syracuse" },
{ name: "Jerami Grant", college: "Syracuse" },

{ name: "LaDainian Tomlinson", college: "TCU" },
{ name: "Andy Dalton", college: "TCU" },
{ name: "Trevon Moehrig", college: "TCU" },
{ name: "Jalen Reagor", college: "TCU" },
{ name: "Desmond Bane", college: "TCU" },
{ name: "Kenrich Williams", college: "TCU" },

{ name: "Peyton Manning", college: "Tennessee" },
{ name: "Alvin Kamara", college: "Tennessee" },
{ name: "Joshua Dobbs", college: "Tennessee" },
{ name: "Cordarrelle Patterson", college: "Tennessee" },
{ name: "Derek Barnett", college: "Tennessee" },
{ name: "Grant Williams", college: "Tennessee" },
{ name: "Tobias Harris", college: "Tennessee" },
{ name: "Josh Richardson", college: "Tennessee" },

{ name: "Kevin Durant", college: "Texas" },
{ name: "LaMarcus Aldridge", college: "Texas" },
{ name: "P.J. Tucker", college: "Texas" },
{ name: "Jarrett Allen", college: "Texas" },
{ name: "Mo Bamba", college: "Texas" },
{ name: "T.J. Ford", college: "Texas" },
{ name: "Colt McCoy", college: "Texas" },
{ name: "Vince Young", college: "Texas" },
{ name: "Bijan Robinson", college: "Texas" },
{ name: "Jordan Hicks", college: "Texas" },
{ name: "Myles Garrett", college: "Texas A&M" },
{ name: "Mike Evans", college: "Texas A&M" },
{ name: "Ryan Tannehill", college: "Texas A&M" },
{ name: "Christian Kirk", college: "Texas A&M" },
{ name: "Von Miller", college: "Texas A&M" },
{ name: "Devin Achane", college: "Texas A&M" },
{ name: "DeAndre Jordan", college: "Texas A&M" },

{ name: "Patrick Mahomes", college: "Texas Tech" },
{ name: "Danny Amendola", college: "Texas Tech" },
{ name: "Wes Welker", college: "Texas Tech" },
{ name: "Michael Crabtree", college: "Texas Tech" },
{ name: "Jarrett Culver", college: "Texas Tech" },
{ name: "Zhaire Smith", college: "Texas Tech" },

{ name: "Troy Aikman", college: "UCLA" },
{ name: "Josh Rosen", college: "UCLA" },
{ name: "Myles Jack", college: "UCLA" },
{ name: "Kenny Clark", college: "UCLA" },
{ name: "Russell Westbrook", college: "UCLA" },
{ name: "Kevin Love", college: "UCLA" },
{ name: "Lonzo Ball", college: "UCLA" },
{ name: "Jrue Holiday", college: "UCLA" },
{ name: "Zach LaVine", college: "UCLA" },
{ name: "Norman Powell", college: "UCLA" },

{ name: "Reggie Bush", college: "USC" },
{ name: "Matt Leinart", college: "USC" },
{ name: "Carson Palmer", college: "USC" },
{ name: "Sam Darnold", college: "USC" },
{ name: "Amon-Ra St. Brown", college: "USC" },
{ name: "Drake London", college: "USC" },
{ name: "JuJu Smith-Schuster", college: "USC" },
{ name: "O.J. Simpson", college: "USC" },
{ name: "DeMar DeRozan", college: "USC" },
{ name: "Evan Mobley", college: "USC" },
{ name: "Isaiah Mobley", college: "USC" },
{ name: "Nikola Vucevic", college: "USC" },

{ name: "Alex Smith", college: "Utah" },
{ name: "Eric Weddle", college: "Utah" },
{ name: "Zack Moss", college: "Utah" },
{ name: "Julian Blackmon", college: "Utah" },
{ name: "Andrew Bogut", college: "Utah" },
{ name: "Kyle Kuzma", college: "Utah" },
{ name: "Jordan Love", college: "Utah State" },
{ name: "Bobby Wagner", college: "Utah State" },
{ name: "Robert Turbin", college: "Utah State" },

{ name: "Jay Cutler", college: "Vanderbilt" },
{ name: "Zach Cunningham", college: "Vanderbilt" },
{ name: "Jordan Matthews", college: "Vanderbilt" },
{ name: "Darius Garland", college: "Vanderbilt" },
{ name: "Aaron Nesmith", college: "Vanderbilt" },
{ name: "Festus Ezeli", college: "Vanderbilt" },

{ name: "Chris Long", college: "Virginia" },
{ name: "Matt Schaub", college: "Virginia" },
{ name: "Heath Miller", college: "Virginia" },
{ name: "Malcolm Brogdon", college: "Virginia" },
{ name: "Joe Harris", college: "Virginia" },
{ name: "De'Andre Hunter", college: "Virginia" },
{ name: "Ty Jerome", college: "Virginia" },

{ name: "Michael Vick", college: "Virginia Tech" },
{ name: "Tyrod Taylor", college: "Virginia Tech" },
{ name: "Logan Thomas", college: "Virginia Tech" },
{ name: "Kam Chancellor", college: "Virginia Tech" },
{ name: "Kyle Fuller", college: "Virginia Tech" },
{ name: "Bruce Smith", college: "Virginia Tech" },
{ name: "Zach LeDay", college: "Virginia Tech" },

{ name: "Dante Pettis", college: "Washington" },
{ name: "Buddha Baker", college: "Washington" },
{ name: "Vita Vea", college: "Washington" },
{ name: "Jake Locker", college: "Washington" },
{ name: "Kelsey Plum", college: "Washington" },
{ name: "Isaiah Stewart", college: "Washington" },
{ name: "Markelle Fultz", college: "Washington" },
{ name: "Gardner Minshew", college: "Washington State" },
{ name: "Brandon Gibson", college: "Washington State" },
{ name: "Dezmon Patmon", college: "Washington State" },
{ name: "Klay Thompson", college: "Washington State" },

{ name: "Pat White", college: "West Virginia" },
{ name: "Tavon Austin", college: "West Virginia" },
{ name: "Geno Smith", college: "West Virginia" },
{ name: "Bruce Irvin", college: "West Virginia" },
{ name: "Jevon Carter", college: "West Virginia" },
{ name: "Miles McBride", college: "West Virginia" },

{ name: "Jonathan Taylor", college: "Wisconsin" },
{ name: "Melvin Gordon", college: "Wisconsin" },
{ name: "Russell Wilson", college: "Wisconsin" },
{ name: "T.J. Watt", college: "Wisconsin" },
{ name: "J.J. Watt", college: "Wisconsin" },
{ name: "Joe Thomas", college: "Wisconsin" },
{ name: "Frank Kaminsky", college: "Wisconsin" },
{ name: "Sam Dekker", college: "Wisconsin" },

{ name: "Josh Allen", college: "Wyoming" },
{ name: "Logan Wilson", college: "Wyoming" },
{ name: "Andrew Wingard", college: "Wyoming" },

{ name: "David West", college: "Xavier" },
{ name: "James Posey", college: "Xavier" },
{ name: "Jordan Crawford", college: "Xavier" },

{ name: "Ryan Fitzpatrick", college: "Harvard" },
{ name: "Jeremy Lin", college: "Harvard" },

{ name: "Paul Atkinson Jr.", college: "Yale" },

];

